// Local host
### Home page
GET http://localhost:5050/

### Authentication
GET http://localhost:5050/login

### All records
GET http://localhost:5050/records

### Single record
GET http://localhost:5050/records/[ID]

### Create record
POST http://localhost:5050/records HTTP/1.1
Content-Type: application/json

{
    "albumName": "Abbey Road",
    "artist": "The Beatles",
    "releaseYear": 1969,
    "genre": "Rock",
    "price": 19.99,
    "description": "The eleventh studio album by The Beatles, featuring iconic tracks like 'Come Together' and 'Here Comes the Sun'.",
    "condition": "Good"
}

### Modify record
PUT http://localhost:5050/records/[ID] HTTP/1.1
Content-Type: application/json

{   
     "albumName": "Abbey Road",
    "artist": "The Beatles",
    "releaseYear": 1969,
    "genre": "Rock",
    "price": 29.99,
     "description": "The eleventh studio album by The Beatles, featuring iconic tracks like 'Come Together' and 'Here Comes the Sun'.",
    "condition": "New"
}

### Delete record
DELETE http://localhost:5050/records/[ID]

### All Inventory
GET http://localhost:5050/inventory

### Single Inventory
GET http://localhost:5050/inventory/[ID]

### Delete Inventory
DELETE http://localhost:5050/inventory/[ID]

### Create User
POST http://localhost:5050/user HTTP/1.1

### Change default password
PUT http://localhost:5050/user/upassword/[ID] HTTP/1.1
Content-Type: application/json

{   
     "newPassword": "test123",
}

### Change role to admin
PUT http://localhost:5050/user/uadmin/[ID] HTTP/1.1

### Change role to User
PUT http://localhost:5050/user/user/[ID] HTTP/1.1

### Delete User
DELETE http://localhost:5050/user/[ID]

### All Users
GET http://localhost:5050/user

### Single Users
GET http://localhost:5050/user/[ID]

### All Order
GET http://localhost:5050/order

### Single Order
GET http://localhost:5050/order/[ID]

### Create Order
POST http://localhost:5050/records HTTP/1.1
Content-Type: application/json

{
    "albumName": "Abbey Road",
    "condition": "Good",
    "quantity" : 1
}

### Change Order Status
PUT http://localhost:5050/order/[ID] HTTP/1.1
Content-Type: application/json

{   
     "status": "Cancelled",
}
### Find Order By User
GET http://localhost:5050/order/user/[ID]

### Delete Order
DELETE http://localhost:5050/user/[ID]




// Render
### Home page
GET https://cse341finalproject-dk7i.onrender.com/

### Authentication
GET https://cse341finalproject-dk7i.onrender.com/login

### All records
GET https://cse341finalproject-dk7i.onrender.com/records

### Single record
GET https://cse341finalproject-dk7i.onrender.com/records/[ID]

### Create record
POST https://cse341finalproject-dk7i.onrender.com/records HTTP/1.1
Content-Type: application/json

{
    "albumName": "Abbey Road",
    "artist": "The Beatles",
    "releaseYear": 1969,
    "genre": "Rock",
    "price": 19.99,
    "description": "The eleventh studio album by The Beatles, featuring iconic tracks like 'Come Together' and 'Here Comes the Sun'.",
    "condition": "Good"
}

### Modify record
PUT https://cse341finalproject-dk7i.onrender.com/records/[ID] HTTP/1.1
Content-Type: application/json

{   
     "albumName": "Abbey Road",
    "artist": "The Beatles",
    "releaseYear": 1969,
    "genre": "Rock",
    "price": 29.99,
     "description": "The eleventh studio album by The Beatles, featuring iconic tracks like 'Come Together' and 'Here Comes the Sun'.",
    "condition": "New"
}

### Delete record
DELETE https://cse341finalproject-dk7i.onrender.com/books/[ID]

### All Inventory
GET https://cse341finalproject-dk7i.onrender.com/inventory

### Single Inventory
GET https://cse341finalproject-dk7i.onrender.com/inventory/[ID]

### Delete Inventory
DELETE http://cse341finalproject-dk7i.onrender.com/inventory/[ID]

### Create User
POST http://cse341finalproject-dk7i.onrender.com/user HTTP/1.1

### Change default password
PUT http://cse341finalproject-dk7i.onrender.com/user/password/[ID] HTTP/1.1
Content-Type: application/json

{   
     "newPassword": "test123",
}

### Change role to admin
PUT http://cse341finalproject-dk7i.onrender.com/user/uadmin/[ID] HTTP/1.1

### Change role to User
PUT http://cse341finalproject-dk7i.onrender.com/user/user/[ID] HTTP/1.1

### Delete User
DELETE http://cse341finalproject-dk7i.onrender.com/user/[ID]

### All Users
GET http://cse341finalproject-dk7i.onrender.com/user

### Single Users
GET http://cse341finalproject-dk7i.onrender.com/user/[ID]

### All Order
GET http://cse341finalproject-dk7i.onrender.com/order

### Single Order
GET http://cse341finalproject-dk7i.onrender.com/order/[ID]

### Create Order
POST http://cse341finalproject-dk7i.onrender.com/records HTTP/1.1
Content-Type: application/json

{
    "albumName": "Abbey Road",
    "condition": "Good",
    "quantity" : 1
}

### Change Order Status
PUT http://cse341finalproject-dk7i.onrender.com/order/[ID] HTTP/1.1
Content-Type: application/json

{   
     "status": "Cancelled",
}
### Find Order By User
GET http://cse341finalproject-dk7i.onrender.com/order/user/[ID]

### Delete Order
DELETE http://cse341finalproject-dk7i.onrender.com/user/[ID]
